### ISSUE TITLE
Throws error when passing in paths

### ISSUE THREAD

**Issue by pawee-del** [MarcoEidinger/SwiftPlantUML#12]
its throws an error saying :Could not read contents of... 
this is the command line i entered : swiftplantuml classdiagram Views Model Controllers

**Comment by MarcoEidinger** [comment]
Hi, I am sorry you encountered this bug in case multiple file paths are passed. I already have a fix for this which will be part of the next minor version. Release is scheduled within the next 36 hours. Stay patient and you'll be rewarded as next minor version (0.3.0) contains lots of goodies with regards to configuration and filtering files/elements.

**Comment by pawee-del** [comment]
Thanks! Its looking good alreat

Kind Regards
Paul Wee
________________________________

**Comment by MarcoEidinger** [comment]
Hi Paul, issue should be fixed. But if you specify incorrect paths then this error can (as expected) occur. You can use `--verbose` option for more details. Feel free to open the issue if you still have trouble with 0.3.0

**Comment by pawee-del** [comment]
where is the binary for the latest release?

**Comment by MarcoEidinger** [comment]
I don't package the binary in the GitHub release artifact but can install the latest version via Homebrew, Mint or install from source. See https://github.com/MarcoEidinger/SwiftPlantUML#installation for details
