### ISSUE TITLE
[Multiple/Missing Xcode] Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed

### ISSUE THREAD

**Issue by pawee-del** [MarcoEidinger/SwiftPlantUML#18]
pwee$ swiftplantuml
Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed: file SourceKittenFramework/library_wrapper.swift, line 31
Illegal instruction: 4

Got the above error when running in a directory with swift files

**Comment by MarcoEidinger** [comment]
Hi, might it be that you have several Versions of Xcode installed in custom path? Or maybe no Xcode at all?

Please check result of `xcode-select -p`.

If Xcode installed under `/Applications/Xcode.app`, please run: 

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

If it's installed elsewhere, please replace the `/Applications/Xcode.app path` in the command above to the location where you've installed Xcode.

**Comment by pawee-del** [comment]
yeap its half working now, when the webpage open, there wasn't any class diagram, even though i entered swiftplantuml classdiagram in the terminal : 
![image](https://user-images.githubusercontent.com/72118587/109893955-b1a79300-7ce0-11eb-8047-9d38dedbf06d.png)

**Comment by MarcoEidinger** [comment]
You probably have too many entities/relationships which would exceed the [default size limitation](https://github.com/MarcoEidinger/SwiftPlantUML#known-limitations) of PlantUML. You can remove those in the editor on planttext.com or use the [configuration options](https://github.com/MarcoEidinger/SwiftPlantUML#configuration) to reduce the number of entities/relationships during script generation.

**Comment by MarcoEidinger** [comment]
I probably will provide more info in the README about
1. Multiple Swift versions
2. how to deal with large diagrams

With respect to (2) online tools like planttext.com are more restrictive than [plantuml.jar](https://plantuml.com/download)

|PlantText output|PlantUML.jar output|
|---|---|
|![sources_planttext](https://user-images.githubusercontent.com/4176826/109912328-ae6cc280-7c60-11eb-9761-fab6c2fc6e4e.png)|![sources_plantumljar](https://user-images.githubusercontent.com/4176826/109912309-a2810080-7c60-11eb-8baf-85585b12984b.png)
|

This diagram consists of 63 entities which were generated by `swiftplantuml ./Sources/` representing the sources of the `SwiftPlantUML` Swift package

PlantUML limits image width and height to 4096. There is a environment variable that you can set to override this limit which in my example is sufficient

![sources_plantumljar_increasedlimit](https://user-images.githubusercontent.com/4176826/109913177-51720c00-7c62-11eb-9757-9d312712c6b5.png)

**Comment by pawee-del** [comment]
how do i get hold of the planttext jar

**Comment by pawee-del** [comment]
i got the jar, how do i run it against my swift folders?

**Comment by MarcoEidinger** [comment]
See the preview of the upcoming documentation describing how to handle large diagrams: https://github.com/MarcoEidinger/SwiftPlantUML/blob/dev/README.md#large-diagrams

**Comment by pawee-del** [comment]
Thanks

it doesn't quite work, it generate an empty sources.txt and open a java run window
here's the terminal screenshot:
![image](https://user-images.githubusercontent.com/72118587/110036425-16bac180-7d91-11eb-8ff5-0026b1213680.png)

my swift file are all under "Compass App" folder

**Comment by MarcoEidinger** [comment]
Might it be that a folder name with space is not correctly handled? Do you get an error when just running

```
`swiftplantuml ./Compass\ App/` --output consoleOnly
```

?? If yes than that's a separate issue. I haven't tested that case

**Comment by pawee-del** [comment]
the output was : Illegal instruction: 4

**Comment by MarcoEidinger** [comment]
Then you probably discovered an issue that `swiftplantuml` does not handle folder for which the folder name contains a space. I created issue https://github.com/MarcoEidinger/SwiftPlantUML/issues/20. In the meantime try to rename your folder and remove the space

**Comment by pawee-del** [comment]
have done that , now another error : 
![image](https://user-images.githubusercontent.com/72118587/110038949-97c78800-7d94-11eb-9e47-04d94cbc1420.png)

`java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:591)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 5 more
java.io.IOException: Cannot run program "/opt/local/bin/dot": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:591)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 5 more
`

**Comment by MarcoEidinger** [comment]
If you are using PlantUML locally then you need Graphviz which is mentioned on PlantUMLs website

**Comment by pawee-del** [comment]
> I probably will provide more info in the README about
> 
> 1. Multiple Swift versions
> 2. how to deal with large diagrams
> 
> With respect to (2) online tools like planttext.com are more restrictive than [plantuml.jar](https://plantuml.com/download)
> 
> PlantText output	PlantUML.jar output
> ![sources_planttext](https://user-images.githubusercontent.com/4176826/109912328-ae6cc280-7c60-11eb-9761-fab6c2fc6e4e.png)	![sources_plantumljar](https://user-images.githubusercontent.com/4176826/109912309-a2810080-7c60-11eb-8baf-85585b12984b.png)
> |
> 
> This diagram consists of 63 entities which were generated by `swiftplantuml ./Sources/` representing the sources of the `SwiftPlantUML` Swift package
> 
> PlantUML limits image width and height to 4096. There is a environment variable that you can set to override this limit which in my example is sufficient
> 
> ![sources_plantumljar_increasedlimit](https://user-images.githubusercontent.com/4176826/109913177-51720c00-7c62-11eb-9757-9d312712c6b5.png)

how did you generate the image?  is it via jar or plantext browser window?

**Comment by MarcoEidinger** [comment]
<img width="1020" alt="Screen Shot 2021-03-04 at 2 44 07 PM" src="https://user-images.githubusercontent.com/4176826/110040726-1ae6d080-7cf8-11eb-9a59-9c8158adccdb.png">

The first image was created in `PlantText` in browser (too many entities to render them all but not too many that PlantText gave up and rendered nothing). Second and third image were generated by PlantUML jar archive locally for a file which I created with `swiftplantuml`
