### ISSUE TITLE
Issue installing the command tool by Brew

### ISSUE THREAD

**Issue by manuelzo** [MarcoEidinger/SwiftPlantUML#25]
Hi Marco,

When I try to install the tool I receive a mismatch on the SHA56 code.

Can you help me?

Tks

**Comment by MarcoEidinger** [comment]
Hi, what's the command you are executing and what is the message you receive? You can also use `brew install swiftplantuml` as I recently added the formulae to homebrew/core

**Comment by manuelzo** [comment]
Input:

brew install MarcoEidinger/formulae/swiftplantuml

Output:

==> Downloading https://github.com/MarcoEidinger/SwiftPlantUML/archive/0.5.0.tar
==> Downloading from https://codeload.github.com/MarcoEidinger/SwiftPlantUML/tar
##O#-#                                                                        
Error: swiftplantuml: SHA256 mismatch
Expected: 9bdfb08563907d44a45b628f75594768e4ed96d065f145424cb97a99ea0b629c
  Actual: 2ba045c719e11d84bb8951b7e352b34e7d459318505f8fc9b1987328de598dff
    File: /Users/manuelzompetta/Library/Caches/Homebrew/downloads/9501921dff39ae35d855a15f1dafd7277c9593472859bf2ba136b20e33401fe0--SwiftPlantUML-0.5.0.tar.gz
To retry an incomplete download, remove the file above.


Best,

M

**Comment by MarcoEidinger** [comment]
Hi Manuel,

thanks for pointing out an error in my homebrew-formulae repo. I did necessary changes so now `brew install MarcoEidinger/formulae/swiftplantuml` will work

**Comment by MarcoEidinger** [comment]
Please re-open if the issue is not yet resolved

**Comment by manuelzo** [comment]
Hi Marco,

Thank you for your feedback.

Now that’s the output I receive:

(base) ***@***.*** ~ % brew install MarcoEidinger/formulae/swiftplantuml
==> Downloading https://github.com/MarcoEidinger/SwiftPlantUML/archive/0.5.1.tar
Already downloaded: /Users/manuelzompetta/Library/Caches/Homebrew/downloads/f450071802e7d0d68f5c3fcc46830066a960e6673faeea1dc252d8951490b8a5--SwiftPlantUML-0.5.1.tar.gz
==> Installing swiftplantuml from marcoeidinger/formulae
==> make install prefix=/opt/homebrew/Cellar/swiftplantuml/0.5.1
Last 15 lines from /Users/manuelzompetta/Library/Logs/Homebrew/swiftplantuml/01.make:
2021-12-14 14:16:11 +0000

make
install
prefix=/opt/homebrew/Cellar/swiftplantuml/0.5.1

error: terminated(72): /usr/bin/xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
    
make: *** [swift-highlight] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/marcoeidinger/homebrew-formulae/issues

(base) ***@***.*** ~ % 

Do you have a solution for that? Thank in advance,

M

**Comment by MarcoEidinger** [comment]
Check if Xcode and the Xcode Command Line Tools are properly installed. https://stackoverflow.com/questions/61501298/xcrun-error-unable-to-find-utility-xctest-not-a-developer-tool-or-in-path

**Comment by manuelzo** [comment]
Tks! In Preferences-Location the dropdown menu was empty.
M
