### ISSUE TITLE
Installing instruction for Homebrew is incomplete

### ISSUE THREAD

**Issue by gerchicovy** [MarcoEidinger/SwiftPlantUML#31]
I'm able to run `brew install swiftplantuml` but when I try to use it I get the following error:
-bash: swiftplantuml: command not found

MacOS 12.1

**Comment by MarcoEidinger** [comment]
To make Homebrew-installed programs available in your shell, you need to add your Homebrew installation location to your $PATH. Have you done that? This is not `swiftplantuml` specific and therefore not listed in the README

**Comment by gerchicovy** [comment]
followed this instruction but it has no effect:
https://sourabhbajaj.com/mac-setup/Homebrew/
And as I understand if I can perform commands `brew ...` then it was configured correctly, wasn't it?

**Comment by MarcoEidinger** [comment]
> And as I understand if I can perform commands brew ... then it was configured correctly, wasn't it?

No, this just means that Homebrew was correctly installed and accessible from $PATH.

Homebrew installs `swiftplantuml` for example in `/usr/local/Cellar/swiftplantuml/0.6.0` and also creates a symlink in `/usr/local/bin`

Please make sure that `usr/local/bin` is part of your $PATH. You chan check this with command `echo $PATH`. 

P.S.: Alternatively you could address the binary directly with `/usr/local/Cellar/swiftplantuml/0.6.0/bin/swiftplantuml --help` ;)

**Comment by gerchicovy** [comment]
>Homebrew installs swiftplantuml for example in /usr/local/Cellar/swiftplantuml/0.6.0 and also creates a symlink in /usr/local/bin
there wasn't "swiftplantuml" but it appeared when I ran "brew install swiftplantuml" again. So somehow it was fixed by itself. Thanks
