### ISSUE TITLE
documentation badge percentage

### ISSUE THREAD

**Issue by dkk** [MarcoEidinger/SwiftPlantUML#32]
Sorry to bother with a question not directly related to the project, but how do you get the percentage on your documentation badge (at the `README.md`)? is it generated by jazzy? is it a real calculated value or is it hardcoded? I could not find where it was calculated. 

<img width="141" alt="Screenshot 2022-05-05 at 13 08 45" src="https://user-images.githubusercontent.com/576723/166911526-6e2b805c-5d8b-44fa-b263-69b38fa6cb9c.png">

**Comment by MarcoEidinger** [comment]
Hi @dkk, yes it is documented by Jazzy. See my article [Brag how good your Swift frameworks are documented](https://blog.eidinger.info/brag-how-good-your-swift-frameworks-are-documented) for more info

**Comment by dkk** [comment]
thanks a lot!
