### ISSUE TITLE
illegal hardware instruction  swiftplantuml

### ISSUE THREAD

**Issue by jemshit** [MarcoEidinger/SwiftPlantUML#33]
Repository i'm trying to get UML of: 
https://github.com/WalletConnect/WalletConnectSwift

Installed SwiftPlantUML via `brew` on macOS

Commands i tried: 
- `swiftplantuml`
- `swiftplantuml classdiagram`
- `swiftplantuml classdiagram Sources`

Error i get:
```bash
SourceKittenFramework/library_wrapper.swift:31: Fatal error: Loading sourcekitd.framework/Versions/A/sourcekitd failed

illegal hardware instruction  swiftplantuml classdiagram Sources
```

**Comment by MarcoEidinger** [comment]
Xcode installation is needed on your Mac. Where have you installed Xcode? If it's installed under `/Applications/Xcode.app`, please run:

`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

If it's installed elsewhere, please replace the `/Applications/Xcode.app` path in the command above to the location where you've installed Xcode.

See also https://github.com/MarcoEidinger/SwiftPlantUML#note-working-with-multiple-swift-versions

**Comment by MarcoEidinger** [comment]
Heads-up: I’ll close the issue beginning of next week unless there is an update from your side

**Comment by MarcoEidinger** [comment]
Closing the issue due to inactivity and solution proposal
