### ISSUE TITLE
Request URI is too long

### ISSUE THREAD

**Issue by aliyasineser** [MarcoEidinger/SwiftPlantUML#36]
Hello,
I am not quite sure if it is a bug or something to improve, but I am trying to export a diagram for the whole project. I get the URL error below:
Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.
Apache/2.4.41 (Ubuntu) Server at planttext.com Port 443

Url is, really pages long because of the codebase size, but I don't know if it is possible to make it otherwise. Should I use the CLI tool for every module or is there a better way of doing it?

Note: I found the output option; if I make it console-only, I can use it. It sounds good to have and I get the UML text exported, however, maybe it is possible to fix the browser options somehow? Wondering if you had the problem in mind. 

Also note, planttext cannot create the big UML diagram that I exported so it is their problem actually.

Thanks in advance, the project is really cool I would like to use it in my career.

**Comment by MarcoEidinger** [comment]
Thanks for your interest in my project. I believe you find the answer by reading https://github.com/MarcoEidinger/SwiftPlantUML#large-diagrams

P.S: I cannot change planttext.com behavior as I don’t own that server/website

**Comment by aliyasineser** [comment]
I'm sorry, I didn't know it wasn't fixable. Thanks for letting me know, I will close the issue and follow the guide you provided. It is a great tool to work on, and I'm sure it will help a lot of devs like me to work better. Cheers ^^
