### ISSUE TITLE
cannot install using home-brew on MacOS10.15.7 with Xcode 12.4

### ISSUE THREAD

**Issue by lionelmichaud** [MarcoEidinger/SwiftPlantUML#4]
I get the message:
Traceback (most recent call last):
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of swiftplantuml formula file from an arbitrary URL is unsupported!  (UsageError)

**Comment by MarcoEidinger** [comment]
Damn, a couple of days ago this was working :( might be homebew 3.0.0 or I have the check-sum wrong. I will check

Please try to build from source in the meantime. Clone the repo, cd into cloned folder and then run `brew install --build-from-source swiftplantuml.rb`. This works for me on MacOS 11.1
