### ISSUE TITLE
canot build the CLI tool

### ISSUE THREAD

**Issue by lionelmichaud** [MarcoEidinger/SwiftPlantUML#5]
I tried to build the CLI tool as described by I get the following error (MacOS 10.15.7):
SwiftPlantUML git:(main) make install
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/jpsim/SourceKitten
Fetching https://github.com/apple/swift-argument-parser.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 5.0.1
Cloning https://github.com/apple/swift-argument-parser.git
Resolving https://github.com/apple/swift-argument-parser.git at 0.3.2
Cloning https://github.com/jpsim/SourceKitten
Resolving https://github.com/jpsim/SourceKitten at 0.31.0
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 4.0.4
[15/15] Linking swiftplantuml
install: : No such file or directory
make: *** [install] Error 71

**Comment by MarcoEidinger** [comment]
I have BigSur (11.1) and building with `make install` works for me after fresh cloning the repo.

<img width="593" alt="Screen Shot 2021-02-08 at 6 45 35 AM" src="https://user-images.githubusercontent.com/4176826/107235214-4d432d80-69d9-11eb-8250-9861ac45ee7d.png">

I use GitHub action to verify `make install` on MacOS 10.15.7 and there it succeeds as well (https://github.com/MarcoEidinger/SwiftPlantUML/runs/1828366272)

Do other `make install` operations work for you? I did a quick Google search for `make: *** [install] Error 71` and often this can be resolved by either using `sudo` or changing the prefix path but all this is then specific to the user's machine and outside of my control

**Comment by MarcoEidinger** [comment]
Closing issue as it appears user-specific.
