### ISSUE TITLE
Command not found when trying to run from command-line

### ISSUE THREAD

**Issue by kdubroff** [MarcoEidinger/SwiftPlantUML#60]
After installing with brew, running `swiftplantuml classdiagram --help` produces `command not found: swiftplantuml`. There is no executable in usr/local/bin (or anywhere on my system that I can find), only an app is installed in the Applications directory and Xcode extension added

**Comment by MarcoEidinger** [comment]
Installation using Homebrew: `brew install swiftplantuml`

Not to be confused with `brew install swiftplantumlapp` that installs the containing app with the Xcode extension

**Comment by kdubroff** [comment]
Thanks, I thought I copy/pasted - not sure how I made that mistake!
