### ISSUE TITLE
“confirms to” should be “conforms to”

### ISSUE THREAD

**Issue by fboundp** [MarcoEidinger/SwiftPlantUML#63]
Throughout the source and generated diagrams, the relationship between a protocol and a type that conforms to the protocol is written as “confirms to”. This is a typo.

Excerpt from <https://docs.swift.org/swift-book/LanguageGuide/Protocols.html>:

> Any type that satisfies the requirements of a protocol is said to _conform_ to that protocol.

**Comment by MarcoEidinger** [comment]
Until I created a patch you can use the following workaround: set a custom text for that relationship type in your `.swiftplantuml.yml` configuration file.

```yml
relationships:
  realize:
    label: "conforms to"
```

**Comment by MarcoEidinger** [comment]
Fix is available in 0.7.3

**Comment by fboundp** [comment]
Thank you!
