### ISSUE TITLE
Feature request: find relationship chains between 2 classes/structs

### ISSUE THREAD

**Issue by Gargo** [MarcoEidinger/SwiftPlantUML#66]
In my case I have a class-container (Class1) and another class (Class2) which is not directly linked with Class1.

Now I need to figure out how to pass Class2 to Class1. It seems the simplest way is:
1)find all the paths between Class1 and Class2 in this generated graph with the specified max lenght in text format
2)find the class container which contains Class1 and Class2 objects (directly or indirectly)

Is it possible to do with your tool?

**Comment by MarcoEidinger** [comment]
@Gargo i don’t understand the feature request. Would you mind elaborating with an example (Swift code)?

**Comment by Gargo** [comment]
@MarcoEidinger For example:

Input:
```
class Class1 {
}

class Class2 {
}

class Container1 {
  var obj1: Class1
  init(_ obj1: Class1) { self.obj1 = obj1 }
}

class Container2 {
  var obj2: Class2!
  init(_ obj2: Class2) { self.obj2 = obj2 }
}

class CommonContainer {
  var container1: Container1!
  var container2: Container2!

  init() { //just shows the creation of relationships between classes/objects
    let obj1 = Class1()
    let obj2 = Class2()
    container1 = Container1(obj1)
    container2 = Container2(obj2)
  }
}
```

User executes command:
```find-path-between-classes Class1 Class2```

Output:
```Class1 - Container1 - Container - Container2 - Class2 ```

How this helps - I see that the nearest common container for Class1 and Class2 is Container and can for example rewrite the code above:
```
//Class1, Container1, Container2 are the same
class Class2 {
  var obj: Class1
  init(_ obj1: Class1) { self.obj1 = obj1 }
}

class CommonContainer {
  var container1: Container1!
  var container2: Container2!

  init() { //just shows the creation of relationships between classes/objects
    let obj1 = Class1()
    let obj2 = Class2(obj1)
    container1 = Container1(obj1)
    container2 = Container2(obj2)
  }
}
```

P.S. I simplified the example. In real code all the "var" variables are declared with corresponding protocol types (SOLID)

**Comment by MarcoEidinger** [comment]
@Gargo thank you for providing the example, I appreciate it! And thank you for your interest i SwiftPlantUML. Unfortunately, I don't want to include that feature in SwiftPlantUML.

If you are interested in building your own tool I recommend utilizing SourceKitten (used by this project) or SwiftSyntax.

Have a great weekend!
