### ISSUE TITLE
Does it support direction configuration

### ISSUE THREAD

**Issue by aelam** [MarcoEidinger/SwiftPlantUML#75]
`top to bottom direction`
`left to right direction`

when the diagram is too wider,  `left to right direction` may help out. Can we set left to right?
https://plantuml.com/use-case-diagram#d551e48d272b2b07

----------------------
Update

test with this setting,  it works

```yml
skinparamCommands: # see https://plantuml.com/skinparam
     - left to right direction
```

**Comment by MarcoEidinger** [comment]
There is no explicit configuration option, but as you found out, you can add the directive as `skinparamCommands` in your `.swiftplantuml.yml` configuration file :)
