### ISSUE TITLE
Generic class with a generic subclass results in a syntax error

### ISSUE THREAD

**Issue by chosa91** [MarcoEidinger/SwiftPlantUML#8]
Hi,

First of all, I would like to thank you, this is a great project and it will help a lot to clarify our architecture and document it.

I've faced with the following syntax error: [link](https://www.planttext.com/?text=UhzxlqDnIM9HIMbk3fUwGd18f8yha7GC2k7Ao4n9LKZDBIYfLCXDpKrABIhcAixEp2j8B4hCLIZEI4p9By_CIrT8IymfJeLhTVLpuUBYIiv9B2vMK79KKaWiLd1Kg5PGuAg52Jg11PsWWauAkherTWgEDg5s2bnS3gbvAK2700000F__0m00)

Code snippet to reproduce:

```swift
class A<U> {}

final class B<U>: A<U> {}
```

**Comment by MarcoEidinger** [comment]
Hi @chosa91 

> First of all, I would like to thank you, this is a great project and it will help a lot to clarify our architecture and document it.

thanks, I am happy to see people find this useful 👍 

> I've faced with the following syntax error: [link](https://www.planttext.com/?text=UhzxlqDnIM9HIMbk3fUwGd18f8yha7GC2k7Ao4n9LKZDBIYfLCXDpKrABIhcAixEp2j8B4hCLIZEI4p9By_CIrT8IymfJeLhTVLpuUBYIiv9B2vMK79KKaWiLd1Kg5PGuAg52Jg11PsWWauAkherTWgEDg5s2bnS3gbvAK2700000F__0m00)

Got it! In the generated PlantUML script I generated the incorrect relationship

| Incorrect      | Correct      |
|------------|-------------|
| ```B --\|> A<U>``` | ```B --\|> A ``` |

I can provide a fix for that in the next couple of days.

In addition I am planning to enhance SwiftPlantUML to visualize generic types and their type constraints. I am planning to add this as [PlantUML supports Generics](https://plantuml.com/class-diagram#b09695ba6d76313d).

But I'd like to get some feedback:
- is this too much clutter?
- should the visualization of generics be configurable?
  - If so then for a class diagram per-se (my preference)or on individual element element level
  
Example

```swift
class A<U> {}

final class B<U>: A<U> {}

struct ObjectItemSwiftUIView<Title: View, SubTitle: View> {}
```

![genericsExample](https://user-images.githubusercontent.com/4176826/108114558-d0095f80-704d-11eb-9b6f-331e99b7b973.png)

**Comment by chosa91** [comment]
Thanks for the quick response & iteration, I'm impressed!

> But I'd like to get some feedback:
> -  is this too much clutter?

I think it isn't too much, but if it can be toggled, I can imagine a use-case where I don't need all the "clutter", just the relations.

> - should the visualization of generics be configurable?
>   - If so then for a class diagram per-se (my preference)or on individual element element level

Configurable in style, what is the idea?

**Comment by MarcoEidinger** [comment]
Good input! 

Being able to define visibility of generics in the style section will _not_ be possible as this section is controlled by PlantUML.

Don't worry, this can be achieved in a separate configuration file (https://github.com/MarcoEidinger/SwiftPlantUML/issues/10) which will be evaluated by SwiftPlantUML during the script generation process. 😄 
The generics information will be added (or not) to the script depending on the configuration setting (`showGenerics: true`).

Overall I am planning to support generics (https://github.com/MarcoEidinger/SwiftPlantUML/issues/9) and its configuration in next minor version.

For the bug fix discussed in this issue I am planning to release a patch soon. I'd hold off updating the [Xcode Source Editor extension](https://github.com/MarcoEidinger/SwiftPlantUML-Xcode-Extension) unless you ask for it.

**Comment by chosa91** [comment]
Thanks for your effort and quick reaction time to the issue. I'm using the CLI tool, so no pressure on the extension side. Nice job!
