### ISSUE TITLE
Syntax error in protocol multiple inheritance with '&' separator

### ISSUE THREAD

**Issue by TTOzzi** [MarcoEidinger/SwiftPlantUML#80]
## Description

Converting a protocol code that inherits multiple protocols separated by '&' into PlantUML text results in a syntax error. 
This does not occur when they are separated by ','.

### Separated by "&"

**input**
```swift
public protocol ResponseSerializer<SerializedObject>: DataResponseSerializerProtocol & DownloadResponseSerializerProtocol { }
```

**output**
```tex
DataResponseSerializerProtocol & DownloadResponseSerializerProtocol <|.. ResponseSerializer : inherits
```

-> Error occurred

<img width="761" alt="스크린샷 2024-02-18 오후 11 05 20" src="https://github.com/MarcoEidinger/SwiftPlantUML/assets/50410213/4b7afd19-195e-4bae-bcc6-1288f2897cce">

### Separated by ","

**input**
```swift
public protocol ResponseSerializer<SerializedObject>: DataResponseSerializerProtocol, DownloadResponseSerializerProtocol { }
```

**output**
```tex
DataResponseSerializerProtocol <|.. ResponseSerializer : conforms to
DownloadResponseSerializerProtocol <|.. ResponseSerializer : conforms to
```

It seems that it should be modified to work the same as when separated by ',' even when separated by '&' 🤔

**Comment by TTOzzi** [comment]
It seems like SourceKitten does not distinguish the '&' character when parsing key.inheritedtypes in the file.

**Comment by MarcoEidinger** [comment]
> It seems like SourceKitten does not distinguish the '&' character when parsing key.inheritedtypes in the file.

Thanks for checking! I was afraid of that 😳I‘ll try with a newer SourceKitten version.. if not fixed then .. I don’t know. I stopped migration to SwiftSyntax but this might be an argument to pick work up again

**Comment by TTOzzi** [comment]
The same issue occurs with the latest version of SourceKitten 🥲
It appears to be a bug with `SourceKit`, so I have reported an issue.  
https://github.com/apple/swift/issues/71753
But... I'm not sure if it can be fixed quickly.

**Comment by MarcoEidinger** [comment]
Thank you @TTOzzi for testing and reporting that issue to Apple!

**Comment by MarcoEidinger** [comment]
Will publish 0.8.1 with your fix soon

**Comment by MarcoEidinger** [comment]
https://github.com/MarcoEidinger/SwiftPlantUML/releases/tag/0.8.1 released

**Comment by TTOzzi** [comment]
Thank you! 😄
