### ISSUE TITLE
QUESTION: Can I run it locally on my laptop instead of using your server?

### ISSUE THREAD

**Issue by SNThunderbolt** [MarcoEidinger/SwiftPlantUML#81]

**Comment by MarcoEidinger** [comment]
Yes, you can :)

![IMG_4248](https://github.com/MarcoEidinger/SwiftPlantUML/assets/4176826/72ff682d-4700-4e6a-ace2-b20a2c22ca6b)

https://github.com/MarcoEidinger/SwiftPlantUML?tab=readme-ov-file#large-diagrams
